version: "2"
services:
  rb1:
    build: .
    ports:
      - "3000:3002"
    volumes:
      - .:/usr/src/hpu
    links:
      - db1
    # This tells the api container to mount 'gems' folder from 'bundle' image
    # to api containers /gems path
    volumes_from:
      - bundle1

  db1:
    image: postgres

  bundle1:
    image: busybox
    volumes:
      - /gems